### ISSUE TITLE
Link to reddit tries to submit story

### ISSUE THREAD

**Issue by bdoserror** [ssumpf/genodian#1]
I can't see it in the source for the article, but on the [web page](https://genodians.org/ssumpf/2022-05-09-telephony) there's a link at the bottom that says "[Discuss at reddit.com/r/genode](https://old.reddit.com/r/genode/submit?url=https://genodians.org/ssumpf/2022-05-09-telephony&title=Pine%20fun%20-%20Telephony%20(_Roger,%20Roger_?))" but it isn't a link to the existing article at reddit (https://www.reddit.com/r/genode/comments/ums54r/pine_fun_telephony_roger_roger/) it's a link that tries to submit the article to Reddit.

**Comment by ssumpf** [comment]
@bdoserror: The Reddit links are meant for comments or discussions only. They use the old Reddit version and they do not work as intended. Somehow one has to submit the article to Reddit first, which was done `jkacher` in this case. So just ignore it for the moment. For articles please refer to `genodians.org` only. The whole thing runs on Genode btw. I hope this answers your question.

**Comment by bdoserror** [comment]
Understood. I didn't have the full context, I found that article via an email newsletter, [A Byte of Coding](https://abyteofcoding.com/), so I wasn't familiar with the site.
